apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: "{{ template "mongodb.name" . }}"
  resources:
    requests:
      memory: 400Mi

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - name: mongodb
    nodePort: 30905
    port: 9090
    protocol: TCP
    targetPort: mongodb
  selector:
    prometheus: prometheus
