{{ if .Values.metrics.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "mongodb.fullname" . }}
  labels:
    app: {{ template "mongodb.fullname" . }}
    prometheus: kube-prometheus
spec:
  jobLabel: {{ template "mongodb.fullname" . }}
  selector:
    matchLabels:
      prometheus: kube-prometheus
  endpoints:
  - port: metrics
    interval: 15s
{{- end }}
