apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongodb.fullname" . }}
  labels:
    app: {{ template "mongodb.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    pipeline_id: "{{ .Values.CI_PIPELINE_ID }}"
    build_id: "{{ .Values.CI_BUILD_ID }}"
    commit_sha: "{{ .Values.CI_COMMIT_SHA }}"
spec:
  # type: {{ .Values.service.type }}
  type: NodePort
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
{{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
  - name: metrics
    port: 9090
    targetPort: metrics
    nodePort: 30906
  selector:
    app: {{ template "mongodb.name" . }}
    release: "{{ .Release.Name }}"
