image: docker:latest
before_script:
  - apk add --no-cache git
services:
  - docker:dind

chart:
  script:
  # Install tool
    - apk add --update git openssl

  # install Helm
    - wget https://kubernetes-helm.storage.googleapis.com/helm-v2.9.1-linux-amd64.tar.gz
    - tar -xvf helm-v2.9.1-linux-amd64.tar.gz
    - mv linux-amd64/helm /usr/local/bin/helm
    - helm init -c

  # update charts
    - git clone https://$GITHUB_USER:$GITHUB_PASSWORD@$GITHUB_REPOSITORY_URL
    - helm package $HELM_PATH
    - mv *.tgz charts/docs
    - helm repo index charts/docs
    - cd charts
    - git add .
    - git config --global user.email "authmicroservice@gmail.com"
    - git config --global user.name "CI bot"
    - git commit -m "Add/Update chart $CI_PROJECT_NAME:$CI_COMMIT_TAG"
    - git push
  only:
    - tags
